# Generated by Django 3.1.7 on 2021-04-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='father',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='garten',
        ),
    ]
