# Generated by Django 3.2 on 2021-04-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210424_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='son',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.kid'),
        ),
    ]
