# Generated by Django 3.2 on 2021-04-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qustion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qustion', models.CharField(max_length=400)),
                ('answer1', models.CharField(max_length=400)),
                ('answer2', models.CharField(max_length=400)),
                ('answer3', models.CharField(max_length=400)),
                ('answer4', models.CharField(max_length=400)),
                ('rightAnswer', models.CharField(max_length=400)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten.quiz')),
            ],
        ),
    ]
