# Generated by Django 3.2 on 2021-04-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0004_auto_20210429_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='Story', max_length=50),
        ),
    ]
