# Generated by Django 3.1.7 on 2021-05-01 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_rate_son'),
        ('kindergarten', '0006_auto_20210501_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('garten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.kindergarten')),
            ],
            options={
                'verbose_name_plural': 'HomeWork',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('option1', models.CharField(max_length=400)),
                ('option2', models.CharField(max_length=400)),
                ('option3', models.CharField(max_length=400)),
                ('option4', models.CharField(max_length=400)),
                ('answer', models.CharField(max_length=400)),
                ('homeWork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten.homework')),
            ],
            options={
                'verbose_name_plural': 'Question',
            },
        ),
    ]
