# Generated by Django 3.1.7 on 2021-05-01 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0008_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='Lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten.lesson'),
        ),
    ]
