# Generated by Django 3.1.7 on 2021-05-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_rate_son'),
        ('kindergarten', '0009_auto_20210501_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='kid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.kid'),
        ),
    ]
