# Generated by Django 3.1.7 on 2021-05-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_rate_son'),
        ('kindergarten', '0011_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.kindergarten')),
            ],
            options={
                'verbose_name_plural': 'Board',
            },
        ),
        migrations.CreateModel(
            name='BoardMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kindergarten.board')),
            ],
            options={
                'verbose_name_plural': 'BoardMessage',
            },
        ),
    ]
