# Generated by Django 3.1.7 on 2021-05-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_rate_son'),
        ('kindergarten', '0012_board_boardmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.kid')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten.story')),
            ],
        ),
    ]
