pipeline {
    agent none
    stages {
stage('Test') {
            agent {
                docker {
                    image 'izaldal/django:team12'
                }
            }
            steps {
                dir("educationweb") {
                
                        sh 'ls'
                        sh 'python manage.py test --keepdb'
                }
            }
            
        }
 stage('Integration Test') {
            agent {
                docker {
                    image 'izaldal/django:team12'
                }
            }
            steps {
                dir("educationweb") {
                        
                        sh 'python manage.py test kindergarten.tests.test_integration --keepdb'
                }
            }
            
        }
 stage('Email Notifications') {
     mail bcc: '', body: '''Hi welcome to jenkins email alerts .
Thanks , bey  ''', cc: '', from: '', replyTo: '', subject: 'Jenkins Job', to: 'education.web.reset@gmail.com'
     
 }



    }
}
