pipeline {
    agent none
    stages {
                stage('Test') {
                            agent {
                                docker {
                                    image 'izaldal/django:izaldal2'
                                }
                            }
                            steps {
                                dir("educationweb") {
                                
                                        sh 'ls'
                                        sh 'python manage.py test --keepdb'
                                }
                            }
                            
                        }
                stage('Integration Test') {
                            agent {
                                docker {
                                    image 'izaldal/django:izaldal2'
                                }
                            }
                            steps {
                                dir("educationweb") {
                                        
                                        sh 'python manage.py test kindergarten.tests.test_integration --keepdb'
                                }
                            }
                            
                        }


                    

                    stage('unit test coverage') {
                            agent {
                                docker {
                                    image 'izaldal/django:izaldal2'
                                }
                            }
                            steps {
                                dir("educationweb") {
                                        
                                        sh 'python -m coverage run manage.py test'
                                        sh 'python -m coverage report'
                                }
                            }
                            
                        }

                    stage('pylint python code convention') {
                            agent {
                                docker {
                                    image 'izaldal/django:izaldal2'
                                }
                            }
                            steps {
                                dir("educationweb/users") {
                                        withEnv(["HOME=${env.WORKSPACE}"])
					{
						sh 'python -m pylint views.py'
						sh "python -m pylint admin.py"
						sh "python -m pylint apps.py"
						sh "python -m pylint models.py"
						sh "python -m pylint tests.py"
						sh "python -m pylint forms.py"
					}
                                }
                            }
                            
                        }


            }

    	post {
		failure{
			mail to: 'education.web.reset@gmail.com',
			subject: "Failed: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']",
			body: "Failed: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']: Check console output at '${env.BUILD_URL}' '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']"
		}
		success{
			mail to: 'education.web.reset@gmail.com',
			subject: "SUCCESS: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']",
			body: "SUCCESS: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']: Check console output at '${env.BUILD_URL}' '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']"
		}

	}
}
